export const SAGA_FETCH_BATHROOMS = "SAGA_FETCH_BATHROOMS";
export const SUCCESS_FETCH_BATHROOMS  = "SUCCESS_FETCH_BATHROOMS";
export const FAILURE_FETCH_BATHROOMS  = "FAILURE_FETCH_BATHROOMS";

export const SAGA_FETCH_BATHROOM = "SAGA_FETCH_BATHROOM";
export const SUCCESS_FETCH_BATHROOM  = "SUCCESS_FETCH_BATHROOM";
export const FAILURE_FETCH_BATHROOM  = "FAILURE_FETCH_BATHROOM";

export const SAGA_FETCH_HOME = "SAGA_FETCH_HOME";
export const SUCCESS_FETCH_HOME  = "SUCCESS_FETCH_HOME";
export const FAILURE_FETCH_HOME  = "FAILURE_FETCH_HOME";
export const EXCLUDE_FIELD_STATE  = "EXCLUDE_FIELD_STATE";

export const SAGA_FETCH_PAGE = "SAGA_FETCH_PAGE";
export const LOAD_FETCH_PAGE = "LOAD_FETCH_PAGE";
export const SUCCESS_FETCH_PAGE  = "SUCCESS_FETCH_PAGE";
export const FAILURE_FETCH_PAGE  = "FAILURE_FETCH_PAGE";
export const PUSH_ROUTE_PAGE = "PUSH_ROUTE_PAGE";

export const SAGA_FETCH_CLASSIFIERS  = "SAGA_FETCH_CLASSIFIERS";
export const LOAD_FETCH_CLASSIFIERS  = "LOAD_FETCH_CLASSIFIERS";
export const SUCCESS_FETCH_CLASSIFIERS  = "SUCCESS_FETCH_CLASSIFIERS";
export const FAILURE_FETCH_CLASSIFIERS  = "FAILURE_FETCH_CLASSIFIERS";

export const SAGA_FETCH_TOP_CATEGORIES  = "SAGA_FETCH_TOP_CATEGORIES";
export const LOAD_FETCH_TOP_CATEGORIES  = "LOAD_FETCH_TOP_CATEGORIES";
export const SUCCESS_FETCH_TOP_CATEGORIES  = "SUCCESS_FETCH_TOP_CATEGORIES";
export const FAILURE_FETCH_TOP_CATEGORIES  = "FAILURE_FETCH_TOP_CATEGORIES";

export const SET_ROUTE = "SET_ROUTE";
export const DROP_ROUTE = "DROP_ROUTE";

export const DROP_FIELD  = "DROP_FIELD";


