export const SAGA_FETCH_BATHROOMS = "SAGA_FETCH_BATHROOMS";
export const SUCCESS_FETCH_BATHROOMS  = "SUCCESS_FETCH_BATHROOMS";
export const FAILURE_FETCH_BATHROOMS  = "FAILURE_FETCH_BATHROOMS";

export const SAGA_FETCH_BATHROOM = "SAGA_FETCH_BATHROOM";
export const SUCCESS_FETCH_BATHROOM  = "SUCCESS_FETCH_BATHROOM";
export const FAILURE_FETCH_BATHROOM  = "FAILURE_FETCH_BATHROOM";

export const SAGA_FETCH_HOME = "SAGA_FETCH_HOME";
export const SUCCESS_FETCH_HOME  = "SUCCESS_FETCH_HOME";
export const FAILURE_FETCH_HOME  = "FAILURE_FETCH_HOME";